import {Col, Container, Row} from "react-bootstrap";
import sharkTankImage from "../images/shark-tank-transparent-background.png"
import Login from "./Login";
import {useDispatch, useSelector} from "react-redux";
import {useCallback, useEffect} from "react";
import { logout } from "../slices/auth";

import EventBus from "../common/EventBus";
import {LinkContainer} from "react-router-bootstrap";

const HomePage = () => {


    const dispatch = useDispatch();
    const { user: currentUser,  isLoggedIn } = useSelector((state) => state.auth);

    const logOut = useCallback(() => {
        console.log("Log out")
        dispatch(logout());
    }, [dispatch]);

    useEffect(() => {


        EventBus.on("logout", () => {
            logOut();
        });

        return () => {
            EventBus.remove("logout");
        };
    }, [currentUser, logOut]);

    return (<div style={{background: "black"}} className="fillmeright fillmeleft">

        <Col lg={4} className="m-auto ">
            <LinkContainer to="/dashboard">
                <a>
                    <img src={sharkTankImage}/>
                </a>
            </LinkContainer>
            <a href="https://www.canva.com/design/DAFxRpTdsQc/sDTQYAiuJOKq80bGgQcilQ/edit?utm_content=DAFxRpTdsQc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton"
               target="blank">
                <p className="text-center" style={{color: "white", fontSize:"x-small"}}>Generated by Canva</p>
            </a>

            <h1 className="text-center" style={{color: "white", fontFamily: "Permanent Marker"}}>Welcome
                {isLoggedIn && " Back"} to Shark
                Tank</h1>
            {isLoggedIn ?
                <>
                    <div className="text-center" style={{color: "white", fontFamily: "Permanent Marker", fontSize:"xxx-large"}}>
                        Team {currentUser.username}</div>
                    <div className="text-center" style={{color: "white",  fontSize:"x-large"}}>
                        Not your team? <a onClick={logOut}>Log out</a></div>
                </>
                : <div className="text-center" style={{color: "white",  fontSize:"x-large"}}>
                    <LinkContainer to="/login"><a >Login</a></LinkContainer></div>}

        </Col>





    </div>)
}

export default HomePage;