import {Col} from "react-bootstrap";
import sharkTankImage from "../images/shark-tank-transparent-background.png"
import {useDispatch, useSelector} from "react-redux";
import {useCallback, useEffect} from "react";
import { logout } from "../slices/auth";

import EventBus from "../common/EventBus";
import {LinkContainer} from "react-router-bootstrap";
import {fetchHackInvestmentTotals} from "../slices/hackInvestmentTotals";


import StockTicker2 from "./StockTicker2";


const HomePage = () => {


    const dispatch = useDispatch();
    const { user: currentUser,  isLoggedIn } = useSelector((state) => state.auth);


    const logOut = useCallback(() => {
        console.log("Log out")
        dispatch(logout());
    }, [dispatch]);

    useEffect(() => {
        dispatch(fetchHackInvestmentTotals());
    }, [])

    useEffect(() => {


        EventBus.on("logout", () => {
            logOut();
        });

        return () => {
            EventBus.remove("logout");
        };
    }, [currentUser, logOut]);

    return (
        <div className="d-flex flex-column min-vh-100">
        <div style={{background: "black"}}  className="container flex-grow-1">

        <Col lg={4} className="m-auto ">
            {isLoggedIn ?
            <LinkContainer to="/invest">
                <a>
                    <img src={sharkTankImage}/>
                </a>
            </LinkContainer> : <img src={sharkTankImage}/>
            }
            <a href="https://www.canva.com/design/DAFxRpTdsQc/sDTQYAiuJOKq80bGgQcilQ/edit?utm_content=DAFxRpTdsQc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton"
               target="blank">
                <p className="text-center" style={{color: "white", fontSize:"x-small"}}>Generated by Canva</p>
            </a>
            {isLoggedIn ?
                <>
                    <div className="text-center" style={{color: "white", fontFamily: "Permanent Marker", fontSize:"x-large"}}>
                        Welcome Back Team {currentUser.username}!</div>
                    <div className="text-center" style={{color: "white",  fontSize:"large"}}>
                        Not your team?  <a onClick={logOut}>Log out</a>
                    </div>
                </>
                : <>
                    <h1 className="text-center" style={{color: "white", fontFamily: "Permanent Marker", fontSize:"xxx-large"}}>
                        Welcome to Shark Tank!</h1>
                    <div className="text-center" style={{color: "white",  fontSize:"large"}}>
                    <LinkContainer to="/login"><a >Login</a></LinkContainer></div>
            </>}
        </Col>
            <div style={{marginTop: "30px"}}>
        <StockTicker2/>
            </div>
        </div>
    </div>)
}

export default HomePage;